<a href="https://colab.research.google.com/github/MONAlIS-A/Tensorflow/blob/main/tensorflow_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

2.19.0


In [3]:
# Initalization of Tensors
X = tf.constant(4)
print(X)

tf.Tensor(4, shape=(), dtype=int32)


In [8]:
X = tf.constant(4,shape=(1,2), dtype=tf.float32)
print(X)

tf.Tensor([[4. 4.]], shape=(1, 2), dtype=float32)


In [9]:
X = tf.constant([[2, 3, 4], [4,5,6]])
print(X)

tf.Tensor(
[[2 3 4]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [11]:
X = tf.ones((3,3))
X

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [12]:
X = tf.zeros((2,3))
X

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [13]:
X = tf.eye(3) # I for the identity matrix (eye)
X

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

In [15]:
X = tf.random.normal((3,3), mean=0, stddev=1)
X

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-1.1662661 ,  1.3667552 , -0.44333547],
       [ 0.40862632,  1.4780214 ,  0.0061664 ],
       [ 1.4391732 ,  0.3375889 ,  0.03621824]], dtype=float32)>

In [16]:
X = tf.random.uniform((1,3), minval=0, maxval=1)
X

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[0.79038405, 0.21017861, 0.39134145]], dtype=float32)>

In [17]:
X = tf.range(9)
X

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=int32)>

In [18]:
X = tf.range(start=1, limit=10, delta=2)
X

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 3, 5, 7, 9], dtype=int32)>

In [20]:
X = tf.cast(X, dtype=tf.float64)
X

<tf.Tensor: shape=(5,), dtype=float64, numpy=array([1., 3., 5., 7., 9.])>

In [21]:
# tf.float(16, 32, 64), tf.int(8, 16, 32, 64), tf.bool

# Mathematical Operations


In [23]:
X = tf.constant([1,2,3])
Y = tf.constant([9,8, 7])

In [24]:
Z = tf.add(X, Y)
Z

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([10, 10, 10], dtype=int32)>

In [26]:
Z = X+Y
Z

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([10, 10, 10], dtype=int32)>

In [27]:
Z = tf.subtract(X, Y)
Z

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([-8, -6, -4], dtype=int32)>

In [28]:
Z = tf.divide(X, Y)
Z

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([0.11111111, 0.25      , 0.42857143])>

In [29]:
Z = tf.multiply(X, Y)
Z


<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 9, 16, 21], dtype=int32)>

In [30]:
Z = tf.tensordot(X, Y, axes=1)
Z

<tf.Tensor: shape=(), dtype=int32, numpy=46>

In [31]:
Z = tf.reduce_sum(X*Y, axis=0)
Z


<tf.Tensor: shape=(), dtype=int32, numpy=46>

In [33]:
Z = tf.reduce_sum(X*Y, axis=0)
Z


<tf.Tensor: shape=(), dtype=int32, numpy=46>

In [34]:
Z = X**5
Z

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([  1,  32, 243], dtype=int32)>

In [35]:
X = tf.random.normal((2,3))
Y = tf.random.normal((3,4))

Z = tf.matmul(X,Y)
Z

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[ 0.67049855, -0.52628255,  3.1044884 , -0.3088237 ],
       [-1.8547684 , -0.85302776, -3.3367307 ,  1.3279667 ]],
      dtype=float32)>

# Indexing

In [37]:
X = tf.constant([0,1,1,2,3,1,2,3])
print(X[:])

tf.Tensor([0 1 1 2 3 1 2 3], shape=(8,), dtype=int32)


In [38]:
print(X[1:])

tf.Tensor([1 1 2 3 1 2 3], shape=(7,), dtype=int32)


In [39]:
print(X[1:3])

tf.Tensor([1 1], shape=(2,), dtype=int32)


In [40]:
print(X[::2])

tf.Tensor([0 1 3 2], shape=(4,), dtype=int32)


In [41]:
print(X[::-1])

tf.Tensor([3 2 1 3 2 1 1 0], shape=(8,), dtype=int32)


In [43]:
indices = tf.constant([0, 3])
X_ind = tf.gather(X, indices)
print(X_ind)

tf.Tensor([0 2], shape=(2,), dtype=int32)


In [44]:
X = tf.constant([[1,2],
                 [3,4],
                 [5,6]])
print(X[0,:])
print(X[0:2,:])

tf.Tensor([1 2], shape=(2,), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


# Reshaping

In [45]:
X = tf.range(9)
print(X)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)


In [46]:
X = tf.reshape(X, (3,3))
print(X)

tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)


In [47]:
X = tf.transpose(X, perm=[1,0])
print(X)

tf.Tensor(
[[0 3 6]
 [1 4 7]
 [2 5 8]], shape=(3, 3), dtype=int32)
